name: MultiJob
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  set_envs:
    runs-on: ubuntu-latest

    env:
      ENV1: "Test Env 1"
      ENV2: "Test Env 2"
      ENV3: "Test Env 3"

    steps:
      - name: Echo Job 1 env variables
        run: |
          echo ENV1=${{ env.ENV1 }} >> test.env
          echo ENV2=${{ env.ENV2 }} >> test.env
          echo ENV3=${{ env.ENV3 }} >> test.env
      - name: Upload env variables
        uses: actions/upload-artifact@v2
        with:
          name: envvars
          path: test.env
  get_envs:
    needs: set_envs
    runs-on: ubuntu-latest

    steps:
      - name: Download env variables
        uses: actions/download-artifact@v1
        with: 
          name: envvars
        run: |
          export $(cat test.env | xargs)
      - name: Echo Job 1 env variables
        run: |
          echo $ENV1
